### ISSUE TITLE
payment submit does not work

### ISSUE THREAD

**Issue by yuma300** [orzFly/ruby-ripple-rest#5]
Payment method is used to work.
But now it is not...
What's wrong?

**Comment by yuma300** [comment]
I got

```
"Cannot POST /v1/payments\n"
```

as a response of payment

**Comment by yuma300** [comment]
I could fix it. I will send pull request.

**Comment by yuma300** [comment]
Please merge this pull request 


https://github.com/orzFly/ruby-ripple-rest/pull/6

**Comment by orzFly** [comment]
Thanks. I also bumped the version to 1.0.4 and registered to RubyGems.org.

**Comment by yuma300** [comment]
Thank you for merging.
